### ISSUE TITLE
Getting error while running test on model endpoint with default configuration generated by CLI

### ISSUE THREAD

**Issue by vasuvanka** [sakuraapi/core#141] opened 2018-02-22 10:29 UTC
While running test on the model endpoint.

``` 

{ message: ’getDb for model \‘UserModel\’ failed because database name \‘user\’ was not defined. Make sure your @Model({dbConfig.db}) is set to a valid database name from your environment config\‘s dbConnections:[{name:\‘...\’}] setting. Also, make sure you\‘ve started SakuraApi, or that you have manually started db connections (e.g. with SakuraMongoDbConnection.connectAll())’ }

```

got this error.route model not able to find the database name.

**Comment by etsuo** [comment] 2018-02-23 05:26
@vasuvanka I'm not able to reproduce your problem, but I am running into an issue where the model isn't available to the `getAllRouteHandler` and the server returns a 500 -- I can confirm that this is a bug, but it may not be what you're experiencing:
```
TypeError: Cannot read property 'constructor' of undefined
    at getAllRouteHandler (/Users/redacted/dev/tmp/test/node_modules/@sakuraapi/core/lib/src/handlers/basic-handlers.js:56:29)
    at Layer.handle [as handle_request] (/Users/redacted/dev/tmp/test/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/redacted/dev/tmp/test/node_modules/express/lib/router/route.js:137:13)
    at routeHandlers (/Users/redacted/dev/tmp/test/node_modules/@sakuraapi/core/lib/src/core/sakura-api.js:146:25)
    at Layer.handle [as handle_request] (/Users/redacted/dev/tmp/test/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/redacted/dev/tmp/test/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/redacted/dev/tmp/test/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/redacted/dev/tmp/test/node_modules/express/lib/router/layer.js:95:5)
    at /Users/redacted/dev/tmp/test/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/redacted/dev/tmp/test/node_modules/express/lib/router/index.js:335:12)
```
@vasuvanka, make sure you configuration is correct. 

Here's what I have:
- `db.ts`
```
export const dbs = {
  user: {
    collection: 'users',
    db: 'user'
  }
};
```
- `environment.ts` (add):
```
  /**
   * Database configurations for SakuraAPI
   */
  dbConnections: [
    {
      mongoClientOptions: {},
      name: dbs.user,
      url
    }
  ],
```
If you have modified how your url is built, make sure that's valid.
- User Mode:
```
@Model({
  dbConfig: dbs.user
})
export class User extends SapiModelMixin() {

  @Db() @Json()
  firstName: string;

  @Db() @Json()
  lastName: string;
}
```
- User Api:
```
@Routable({
  baseUrl: 'user',
  model: User
})
export class UserApi extends SapiRoutableMixin() {
}
```
- User Api Test:
```
import {SakuraApi}  from '@sakuraapi/core';
import * as request from 'supertest';
import {
  testSapi,
  testUrl
}                   from '../../spec/helpers/sakura-api';
import {UserApi}    from './user-api';

describe('UserApi tests', () => {
  let sapi: SakuraApi;

  beforeEach(async (done) => {
    try {

      sapi = testSapi({
        routables: [UserApi]
      });

      await sapi.listen({bootMessage: ''});

      done();
    } catch (err) {
      done.fail(err);
    }
  });

  afterEach(async (done) => {
    try {
      await sapi.close();
      done();
    } catch (err) {
      done.fail(err);
    }
  });

  it('GET /user', async (done) => {

    try {
      const result = await request(sapi.app)
        .get(testUrl('/user', sapi))
        .expect(200);

      console.log(`------------------------`);
      console.log(result.body);

      done();
    } catch (err) {
      done.fail(err);
    }
  });
});
```

**Comment by vasuvanka** [comment] 2018-02-23 06:03
@etsuo , 
Here is the steps to reproduce
1) config db
2) config model
3) Set route on a model , suppose model is `users`

Here is the test code for users crud api 
when both model and route injected.


describe('UserApi tests', () => {
  const sapi = testSapi({
    models: [UserModel],
    routables: [UserApi]
  });

  beforeAll(async (done) => {
    try {
      await sapi
        .dbConnections
        .connectAll();

      await sapi.listen({bootMessage: ''});
      done();
    } catch (err) {
      done.fail(err);
    }

  });

  afterAll(async (done) => {
    try {
      await sapi.close();
      done();
    } catch (err) {
      done.fail(err);
    }
  });

  it('UserApi GET:/users', async (done) => {
    try {
      const result = await request(sapi.app)
        .get(testUrl('/users', sapi))
        .expect(200);
      expect(result.body.length).toBe(0);
      done();
    } catch (err) {
      done.fail(err);
    }
  });
});

**Comment by etsuo** [comment] 2018-02-23 06:27
@vasuvanka help me understand how that's different than what I posted in the comment prior? I want to make sure I'm not missing anything. You actually don't need to call `sapi.dbConnections.connectAll()` before calling `sapi.listen` -- `listen` will initialize the db connections if it determines that has not yet been done. You can manually tell SakuraApi to connect to the db before listening if you need to do some db work before starting the web server. 

Unless there's something different with what I listed [here](https://github.com/sakuraapi/core/issues/141#issuecomment-367913633), then I believe your problem is that your configuration isn't right. Double check using the example I gave above.

However, there is still the other error I ran into even with the example above (the `TypeError: Cannot read property 'constructor' of undefined` error). I committed some tests on the `hotfix/141` branch to try to cause the same kind of error in the tests for `getAllRouteHandler`, but it seems to be working fine in those test.

One thing I noticed is that this feature (the auto-creation of CRUD endpoints if you define a model on a  routable) has very little testing in the core code.

Let me know if you double checked all your configuration and if you're still getting the DB error. Once you get past the DB error, please also let me know if you are also getting the constructor error.

Thanks.

**Comment by etsuo** [comment] 2018-02-23 08:08
@vasuvanka please disregard the prior request.

I was not getting the same error because I forgot to inject the model into SakuraApi. With that correct, I have been able to reliably reproduce your issue. I'll continue to investigate the cause.

**Comment by etsuo** [comment] 2018-02-23 10:22
Turns out this was a configuration problem. I forgot to add the config `dbConnections` to spec environment.

We definitely need better documentation around this stuff, and there are certainly some errors that could be more helpful. That said, however, I think this is primarily a configuration issue, not a bug. I have shared a project that "shows my work" to get this working off a `sapi` scaffolded project. You can find that (for the moment) here: https://github.com/etsuo/sapi-test

@vasuvanka let me know if you get it working. Thanks for the feedback - this has led to insights that will improve the project.

**Comment by gowthamrodda** [comment] 2018-02-23 11:11
@etsuo @vasuvanka I just cloned the project https://github.com/etsuo/sapi-test and its working fine. Thanks for the quick test project.

**Comment by vasuvanka** [comment] 2018-02-23 11:23
@etsuo thank you for test project configuration.trying to figure out what went wrong.

**Comment by etsuo** [comment] 2018-02-28 22:11
@vasuvanka were you able to figure out what went wrong? Should I close this ticket?

**Comment by vasuvanka** [comment] 2018-03-04 04:20
Hi, @etsuo still can't able to figure it out what exactly went wrong.getting error as 

  - Failed: getDb for model 'UserModel' failed because database name 'test' was not defined. Make sure your @Model({dbConfig.db}) is set to a valid database name from your environment config's dbConnections:[{name:'...'}] setting. Also, make sure you've started SakuraApi, or that you have manually started db connections (e.g. with SakuraMongoDbConnection.connectAll())

compared script files and configuration with https://github.com/etsuo/sapi-test but can't able to figure it out.

**Comment by etsuo** [comment] 2018-03-04 04:24
@vasuvanka, ok, no problem. To be clear though, the sample I sent you is working, correct?

**Comment by vasuvanka** [comment] 2018-03-04 04:37
Yes it is working @etsuo

**Comment by etsuo** [comment] 2018-03-04 04:39
ok thanks for the update @vasuvanka. Is there any more work to be done with this ticket or should we close it?

**Closed** 2018-03-04 07:18 UTC
Labels: in progress, question

**Comment by etsuo** [comment] 2018-03-04 17:44
Thanks for the feedback @vasuvanka and for working through this ticket with me.
